OpenJDK installation instructions for MacOS
koushikkothagal/java-backend-bootcamp pull request #18
Opened 2023-01-28 08:44 UTC by ryanohcodes

Hey Koushik. I have listed out how to install Java from OpenJDK with annotated pictures. Please let me know if there are any deficiencies or if you would like me to add more. Please and thank you.

2023-01-28 20:35 UTC, koushikkothagal requested changes
Thanks for the thorough steps. Since you are using Terminal commands, can I request you to replace the screenshots with terminal code blocks instead? Use this syntax:

~~~
```sh
$ java -version
openjdk version 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
```
~~~

And It will show up like this:

```sh
$ java -version
openjdk version 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
```

You can replace all terminal screenshots with this. Use `$ ` to indicate a prompt, like I have done in the example above.

2023-01-28 20:35 UTC, koushikkothagal commented on session-02-big-picture/README.md
> +   M1 processor: Click on "tar.gz" to the right of "macOS/AArch64".
```suggestion
   Apple Silicon processor: Click on "tar.gz" to the right of "macOS/AArch64". 
```

2023-01-29 03:44 UTC, ryanohcodes commented
Thank you for the lesson. I have implemented your comments and suggestions. Please review the changes.

2023-02-02 06:32 UTC, koushikkothagal approved these changes

2023-02-02 06:32 UTC, merged